try this

diff --git a/.github/workflows/clojure.yml b/.github/workflows/clojure.yml
--- a/.github/workflows/clojure.yml
+++ b/.github/workflows/clojure.yml
@@ -188,8 +188,11 @@ jobs:
       run: clojure -T:build compile-java
 
     - name: Check annotations
+      working-directory: server
       run: |
-        echo "::error file=server/test/instant/config_edn_test.clj,line=24::FAIL in demonstrate-failure-check (config_edn_test.clj:24)%0Aexpected: {:hello :world, :large :data, :struct :ture, :that [:takes :multiple :lines]}%0A  actual: {:something-else {:hello :world, :large :data, :struct :ture, :that [:takes :multiple :lines]}}"
+        echo "::error file=.github/workflows/clojure.yml,line=193::error"
+        echo "::error file=server/test/instant/config_edn_test.clj,line=24::test failure"
+        exit 1
 
 
     - name: Run Clojure tests
